<?php
/**
 * AccountBalancesDto
 *
 * PHP version 8.1
 *
 * @package  Shaype\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notification Webhooks
 *
 * Definition of the webhooks API for client callbacks
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shaype\Webhook\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Shaype\Webhook\ObjectSerializer;

/**
 * AccountBalancesDto Class Doc Comment
 *
 * @description Breakdown of the account balances
 * @package  Shaype\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AccountBalancesDto implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'AccountBalancesDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'total_balance' => '\Shaype\Webhook\Model\CurrencyAmount',
        'held_balance' => '\Shaype\Webhook\Model\CurrencyAmount',
        'locked_balance' => '\Shaype\Webhook\Model\CurrencyAmount',
        'stacks_balance' => '\Shaype\Webhook\Model\CurrencyAmount',
        'available_balance' => '\Shaype\Webhook\Model\CurrencyAmount'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'total_balance' => null,
        'held_balance' => null,
        'locked_balance' => null,
        'stacks_balance' => null,
        'available_balance' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'total_balance' => false,
        'held_balance' => false,
        'locked_balance' => false,
        'stacks_balance' => false,
        'available_balance' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'total_balance' => 'totalBalance',
        'held_balance' => 'heldBalance',
        'locked_balance' => 'lockedBalance',
        'stacks_balance' => 'stacksBalance',
        'available_balance' => 'availableBalance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'total_balance' => 'setTotalBalance',
        'held_balance' => 'setHeldBalance',
        'locked_balance' => 'setLockedBalance',
        'stacks_balance' => 'setStacksBalance',
        'available_balance' => 'setAvailableBalance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'total_balance' => 'getTotalBalance',
        'held_balance' => 'getHeldBalance',
        'locked_balance' => 'getLockedBalance',
        'stacks_balance' => 'getStacksBalance',
        'available_balance' => 'getAvailableBalance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('total_balance', $data ?? [], null);
        $this->setIfExists('held_balance', $data ?? [], null);
        $this->setIfExists('locked_balance', $data ?? [], null);
        $this->setIfExists('stacks_balance', $data ?? [], null);
        $this->setIfExists('available_balance', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_balance
     *
     * @return \Shaype\Webhook\Model\CurrencyAmount|null
     */
    public function getTotalBalance(): ?\Shaype\Webhook\Model\CurrencyAmount
    {
        return $this->container['total_balance'];
    }

    /**
     * Sets total_balance
     *
     * @param \Shaype\Webhook\Model\CurrencyAmount|null $total_balance total_balance
     *
     * @return $this
     */
    public function setTotalBalance(?\Shaype\Webhook\Model\CurrencyAmount $total_balance): static
    {
        if (is_null($total_balance)) {
            throw new InvalidArgumentException('non-nullable total_balance cannot be null');
        }
        $this->container['total_balance'] = $total_balance;

        return $this;
    }

    /**
     * Gets held_balance
     *
     * @return \Shaype\Webhook\Model\CurrencyAmount|null
     */
    public function getHeldBalance(): ?\Shaype\Webhook\Model\CurrencyAmount
    {
        return $this->container['held_balance'];
    }

    /**
     * Sets held_balance
     *
     * @param \Shaype\Webhook\Model\CurrencyAmount|null $held_balance held_balance
     *
     * @return $this
     */
    public function setHeldBalance(?\Shaype\Webhook\Model\CurrencyAmount $held_balance): static
    {
        if (is_null($held_balance)) {
            throw new InvalidArgumentException('non-nullable held_balance cannot be null');
        }
        $this->container['held_balance'] = $held_balance;

        return $this;
    }

    /**
     * Gets locked_balance
     *
     * @return \Shaype\Webhook\Model\CurrencyAmount|null
     */
    public function getLockedBalance(): ?\Shaype\Webhook\Model\CurrencyAmount
    {
        return $this->container['locked_balance'];
    }

    /**
     * Sets locked_balance
     *
     * @param \Shaype\Webhook\Model\CurrencyAmount|null $locked_balance locked_balance
     *
     * @return $this
     */
    public function setLockedBalance(?\Shaype\Webhook\Model\CurrencyAmount $locked_balance): static
    {
        if (is_null($locked_balance)) {
            throw new InvalidArgumentException('non-nullable locked_balance cannot be null');
        }
        $this->container['locked_balance'] = $locked_balance;

        return $this;
    }

    /**
     * Gets stacks_balance
     *
     * @return \Shaype\Webhook\Model\CurrencyAmount|null
     */
    public function getStacksBalance(): ?\Shaype\Webhook\Model\CurrencyAmount
    {
        return $this->container['stacks_balance'];
    }

    /**
     * Sets stacks_balance
     *
     * @param \Shaype\Webhook\Model\CurrencyAmount|null $stacks_balance stacks_balance
     *
     * @return $this
     */
    public function setStacksBalance(?\Shaype\Webhook\Model\CurrencyAmount $stacks_balance): static
    {
        if (is_null($stacks_balance)) {
            throw new InvalidArgumentException('non-nullable stacks_balance cannot be null');
        }
        $this->container['stacks_balance'] = $stacks_balance;

        return $this;
    }

    /**
     * Gets available_balance
     *
     * @return \Shaype\Webhook\Model\CurrencyAmount|null
     */
    public function getAvailableBalance(): ?\Shaype\Webhook\Model\CurrencyAmount
    {
        return $this->container['available_balance'];
    }

    /**
     * Sets available_balance
     *
     * @param \Shaype\Webhook\Model\CurrencyAmount|null $available_balance available_balance
     *
     * @return $this
     */
    public function setAvailableBalance(?\Shaype\Webhook\Model\CurrencyAmount $available_balance): static
    {
        if (is_null($available_balance)) {
            throw new InvalidArgumentException('non-nullable available_balance cannot be null');
        }
        $this->container['available_balance'] = $available_balance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


