<?php
/**
 * BatchCompletedEventDto
 *
 * PHP version 8.1
 *
 * @package  Shaype\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notification Webhooks
 *
 * Definition of the webhooks API for client callbacks
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shaype\Webhook\Model;

/**
 * BatchCompletedEventDto Class Doc Comment
 *
 * @description Details of the **Bulk-Batch Completed** event; provided when the type is &#x60;BATCH_COMPLETED&#x60;.
 * @package  Shaype\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class BatchCompletedEventDto extends EventDetailsDto
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'BatchCompletedEventDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'batch_id' => 'string',
        'batch_type' => 'string',
        'received_at_utc' => '\DateTime',
        'finished_at_utc' => '\DateTime',
        'status' => 'string',
        'item_statistics' => '\Shaype\Webhook\Model\ItemStatisticsDto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'batch_id' => 'uuid',
        'batch_type' => null,
        'received_at_utc' => 'date-time',
        'finished_at_utc' => 'date-time',
        'status' => null,
        'item_statistics' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'batch_id' => false,
        'batch_type' => false,
        'received_at_utc' => false,
        'finished_at_utc' => false,
        'status' => false,
        'item_statistics' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables + parent::openAPINullables();
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'batch_id' => 'batchId',
        'batch_type' => 'batchType',
        'received_at_utc' => 'receivedAtUtc',
        'finished_at_utc' => 'finishedAtUtc',
        'status' => 'status',
        'item_statistics' => 'itemStatistics'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'batch_id' => 'setBatchId',
        'batch_type' => 'setBatchType',
        'received_at_utc' => 'setReceivedAtUtc',
        'finished_at_utc' => 'setFinishedAtUtc',
        'status' => 'setStatus',
        'item_statistics' => 'setItemStatistics'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'batch_id' => 'getBatchId',
        'batch_type' => 'getBatchType',
        'received_at_utc' => 'getReceivedAtUtc',
        'finished_at_utc' => 'getFinishedAtUtc',
        'status' => 'getStatus',
        'item_statistics' => 'getItemStatistics'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const STATUS_RECEIVED = 'RECEIVED';
    public const STATUS_PROCESSING = 'PROCESSING';
    public const STATUS_COMPLETED = 'COMPLETED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getStatusAllowableValues()
    {
        return [
            self::STATUS_RECEIVED,
            self::STATUS_PROCESSING,
            self::STATUS_COMPLETED,
        ];
    }


    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        parent::__construct($data);

        $this->setIfExists('batch_id', $data ?? [], null);
        $this->setIfExists('batch_type', $data ?? [], null);
        $this->setIfExists('received_at_utc', $data ?? [], null);
        $this->setIfExists('finished_at_utc', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('item_statistics', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets batch_id
     *
     * @return string|null
     */
    public function getBatchId(): ?string
    {
        return $this->container['batch_id'];
    }

    /**
     * Sets batch_id
     *
     * @param string|null $batch_id Unique identifier (UUID) of the Batch-completed associated with the event.
     *
     * @return $this
     */
    public function setBatchId(?string $batch_id): static
    {
        if (is_null($batch_id)) {
            throw new InvalidArgumentException('non-nullable batch_id cannot be null');
        }
        $this->container['batch_id'] = $batch_id;

        return $this;
    }

    /**
     * Gets batch_type
     *
     * @return string|null
     */
    public function getBatchType(): ?string
    {
        return $this->container['batch_type'];
    }

    /**
     * Sets batch_type
     *
     * @param string|null $batch_type Batch type associated to the completed event.
     *
     * @return $this
     */
    public function setBatchType(?string $batch_type): static
    {
        if (is_null($batch_type)) {
            throw new InvalidArgumentException('non-nullable batch_type cannot be null');
        }
        $this->container['batch_type'] = $batch_type;

        return $this;
    }

    /**
     * Gets received_at_utc
     *
     * @return \DateTime|null
     */
    public function getReceivedAtUtc(): ?\DateTime
    {
        return $this->container['received_at_utc'];
    }

    /**
     * Sets received_at_utc
     *
     * @param \DateTime|null $received_at_utc DateTime of when the batch was created
     *
     * @return $this
     */
    public function setReceivedAtUtc(?\DateTime $received_at_utc): static
    {
        if (is_null($received_at_utc)) {
            throw new InvalidArgumentException('non-nullable received_at_utc cannot be null');
        }
        $this->container['received_at_utc'] = $received_at_utc;

        return $this;
    }

    /**
     * Gets finished_at_utc
     *
     * @return \DateTime|null
     */
    public function getFinishedAtUtc(): ?\DateTime
    {
        return $this->container['finished_at_utc'];
    }

    /**
     * Sets finished_at_utc
     *
     * @param \DateTime|null $finished_at_utc DateTime of when the batch was processed and completed
     *
     * @return $this
     */
    public function setFinishedAtUtc(?\DateTime $finished_at_utc): static
    {
        if (is_null($finished_at_utc)) {
            throw new InvalidArgumentException('non-nullable finished_at_utc cannot be null');
        }
        $this->container['finished_at_utc'] = $finished_at_utc;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Batch status.
     *
     * @return $this
     */
    public function setStatus(?string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets item_statistics
     *
     * @return \Shaype\Webhook\Model\ItemStatisticsDto|null
     */
    public function getItemStatistics(): ?\Shaype\Webhook\Model\ItemStatisticsDto
    {
        return $this->container['item_statistics'];
    }

    /**
     * Sets item_statistics
     *
     * @param \Shaype\Webhook\Model\ItemStatisticsDto|null $item_statistics Batch-item processed statistics.
     *
     * @return $this
     */
    public function setItemStatistics(?\Shaype\Webhook\Model\ItemStatisticsDto $item_statistics): static
    {
        if (is_null($item_statistics)) {
            throw new InvalidArgumentException('non-nullable item_statistics cannot be null');
        }
        $this->container['item_statistics'] = $item_statistics;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


