<?php
/**
 * NotificationsAPIApi
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notification Webhooks
 *
 * Definition of the webhooks API for client callbacks
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * NotificationsAPIApi Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationsAPIApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'notifyEmail' => [
            'application/json',
        ],
        'notifyNotification' => [
            'application/json',
        ],
        'notifySms' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation notifyEmail
     *
     * Notification - email
     *
     * @param  \OpenAPI\Client\Model\EmailDto $email_dto email_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyEmail'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function notifyEmail(
        \OpenAPI\Client\Model\EmailDto $email_dto,
        string $contentType = self::contentTypes['notifyEmail'][0]
    ): void
    {
        $this->notifyEmailWithHttpInfo($email_dto, $contentType);
    }

    /**
     * Operation notifyEmailWithHttpInfo
     *
     * Notification - email
     *
     * @param  \OpenAPI\Client\Model\EmailDto $email_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyEmail'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function notifyEmailWithHttpInfo(
        \OpenAPI\Client\Model\EmailDto $email_dto,
        string $contentType = self::contentTypes['notifyEmail'][0]
    ): array
    {
        $request = $this->notifyEmailRequest($email_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation notifyEmailAsync
     *
     * Notification - email
     *
     * @param  \OpenAPI\Client\Model\EmailDto $email_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyEmail'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function notifyEmailAsync(
        \OpenAPI\Client\Model\EmailDto $email_dto,
        string $contentType = self::contentTypes['notifyEmail'][0]
    ): PromiseInterface
    {
        return $this->notifyEmailAsyncWithHttpInfo($email_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation notifyEmailAsyncWithHttpInfo
     *
     * Notification - email
     *
     * @param  \OpenAPI\Client\Model\EmailDto $email_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyEmail'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function notifyEmailAsyncWithHttpInfo(
        $email_dto,
        string $contentType = self::contentTypes['notifyEmail'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->notifyEmailRequest($email_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'notifyEmail'
     *
     * @param  \OpenAPI\Client\Model\EmailDto $email_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyEmail'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function notifyEmailRequest(
        $email_dto,
        string $contentType = self::contentTypes['notifyEmail'][0]
    ): Request
    {

        // verify the required parameter 'email_dto' is set
        if ($email_dto === null || (is_array($email_dto) && count($email_dto) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $email_dto when calling notifyEmail'
            );
        }


        $resourcePath = '/api/hay/v0/communications/email';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($email_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($email_dto));
            } else {
                $httpBody = $email_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation notifyNotification
     *
     * Notification - event
     *
     * @param  \OpenAPI\Client\Model\NotificationDto $notification_dto notification_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyNotification'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function notifyNotification(
        \OpenAPI\Client\Model\NotificationDto $notification_dto,
        string $contentType = self::contentTypes['notifyNotification'][0]
    ): void
    {
        $this->notifyNotificationWithHttpInfo($notification_dto, $contentType);
    }

    /**
     * Operation notifyNotificationWithHttpInfo
     *
     * Notification - event
     *
     * @param  \OpenAPI\Client\Model\NotificationDto $notification_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyNotification'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function notifyNotificationWithHttpInfo(
        \OpenAPI\Client\Model\NotificationDto $notification_dto,
        string $contentType = self::contentTypes['notifyNotification'][0]
    ): array
    {
        $request = $this->notifyNotificationRequest($notification_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation notifyNotificationAsync
     *
     * Notification - event
     *
     * @param  \OpenAPI\Client\Model\NotificationDto $notification_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyNotification'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function notifyNotificationAsync(
        \OpenAPI\Client\Model\NotificationDto $notification_dto,
        string $contentType = self::contentTypes['notifyNotification'][0]
    ): PromiseInterface
    {
        return $this->notifyNotificationAsyncWithHttpInfo($notification_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation notifyNotificationAsyncWithHttpInfo
     *
     * Notification - event
     *
     * @param  \OpenAPI\Client\Model\NotificationDto $notification_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyNotification'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function notifyNotificationAsyncWithHttpInfo(
        $notification_dto,
        string $contentType = self::contentTypes['notifyNotification'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->notifyNotificationRequest($notification_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'notifyNotification'
     *
     * @param  \OpenAPI\Client\Model\NotificationDto $notification_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifyNotification'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function notifyNotificationRequest(
        $notification_dto,
        string $contentType = self::contentTypes['notifyNotification'][0]
    ): Request
    {

        // verify the required parameter 'notification_dto' is set
        if ($notification_dto === null || (is_array($notification_dto) && count($notification_dto) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $notification_dto when calling notifyNotification'
            );
        }


        $resourcePath = '/api/hay/v0/communications/notification';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($notification_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($notification_dto));
            } else {
                $httpBody = $notification_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation notifySms
     *
     * Notification - SMS
     *
     * @param  \OpenAPI\Client\Model\SmsDto $sms_dto sms_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifySms'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function notifySms(
        \OpenAPI\Client\Model\SmsDto $sms_dto,
        string $contentType = self::contentTypes['notifySms'][0]
    ): void
    {
        $this->notifySmsWithHttpInfo($sms_dto, $contentType);
    }

    /**
     * Operation notifySmsWithHttpInfo
     *
     * Notification - SMS
     *
     * @param  \OpenAPI\Client\Model\SmsDto $sms_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifySms'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function notifySmsWithHttpInfo(
        \OpenAPI\Client\Model\SmsDto $sms_dto,
        string $contentType = self::contentTypes['notifySms'][0]
    ): array
    {
        $request = $this->notifySmsRequest($sms_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation notifySmsAsync
     *
     * Notification - SMS
     *
     * @param  \OpenAPI\Client\Model\SmsDto $sms_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifySms'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function notifySmsAsync(
        \OpenAPI\Client\Model\SmsDto $sms_dto,
        string $contentType = self::contentTypes['notifySms'][0]
    ): PromiseInterface
    {
        return $this->notifySmsAsyncWithHttpInfo($sms_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation notifySmsAsyncWithHttpInfo
     *
     * Notification - SMS
     *
     * @param  \OpenAPI\Client\Model\SmsDto $sms_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifySms'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function notifySmsAsyncWithHttpInfo(
        $sms_dto,
        string $contentType = self::contentTypes['notifySms'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->notifySmsRequest($sms_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'notifySms'
     *
     * @param  \OpenAPI\Client\Model\SmsDto $sms_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['notifySms'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function notifySmsRequest(
        $sms_dto,
        string $contentType = self::contentTypes['notifySms'][0]
    ): Request
    {

        // verify the required parameter 'sms_dto' is set
        if ($sms_dto === null || (is_array($sms_dto) && count($sms_dto) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $sms_dto when calling notifySms'
            );
        }


        $resourcePath = '/api/hay/v0/communications/sms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sms_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sms_dto));
            } else {
                $httpBody = $sms_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
