<?php
/**
 * BatchCompletedEventDtoTest
 *
 * PHP version 8.1
 *
 * @package  Shaype\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notification Webhooks
 *
 * Definition of the webhooks API for client callbacks
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Shaype\Webhook\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BatchCompletedEventDtoTest Class Doc Comment
 *
 * @description Details of the **Bulk-Batch Completed** event; provided when the type is &#x60;BATCH_COMPLETED&#x60;.
 * @package     Shaype\Webhook
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BatchCompletedEventDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BatchCompletedEventDto"
     */
    public function testBatchCompletedEventDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "batch_id"
     */
    public function testPropertyBatchId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "batch_type"
     */
    public function testPropertyBatchType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "received_at_utc"
     */
    public function testPropertyReceivedAtUtc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "finished_at_utc"
     */
    public function testPropertyFinishedAtUtc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "item_statistics"
     */
    public function testPropertyItemStatistics()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
