<?php
/**
 * DelegatedOtpNotificationEventDtoTest
 *
 * PHP version 8.1
 *
 * @package  Shaype\Webhook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notification Webhooks
 *
 * Definition of the webhooks API for client callbacks
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Shaype\Webhook\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DelegatedOtpNotificationEventDtoTest Class Doc Comment
 *
 * @description Details of the **Delegated OTP Notification** event; provided when the type is &#x60;DELEGATED_OTP_NOTIFICATION&#x60;.
 * @package     Shaype\Webhook
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DelegatedOtpNotificationEventDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DelegatedOtpNotificationEventDto"
     */
    public function testDelegatedOtpNotificationEventDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "card_id"
     */
    public function testPropertyCardId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merchant_info"
     */
    public function testPropertyMerchantInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transaction_info"
     */
    public function testPropertyTransactionInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passcode"
     */
    public function testPropertyPasscode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
